server:
#  servlet:
#    context-path: /api
  port: 8111

spring:

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/flashsaleusers
    username: root
    password: ucd21213011.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

springdoc:
  api-docs:
    path: /api-docs

