server:
#  servlet:
#    context-path: /api
  port: 8111

spring:

  cloud:
    nacos:
      discovery:
        server-addr: 52.215.184.45:8848

  application:
    name: user-service

  datasource:
    url: jdbc:mysql://flashsaledb.ccbk1nkjxq6v.eu-west-1.rds.amazonaws.com:3306/flashsaleusers
    username: admin
    password: PASSWORD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

springdoc:
  api-docs:
    path: /api-docs

