server:
#  servlet:
#    context-path: /api
  port: 8101

spring:

  datasource:
    url: jdbc:mysql://flashsaledb.ccbk1nkjxq6v.eu-west-1.rds.amazonaws.com:3306/flashsalesellers
    username: admin
    password: PASSWORD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

springdoc:
  api-docs:
    path: /api-docs

