#server:
#  port: 8091
#spring:
#  application:
#    name: order-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///shop-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: admin
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
#  servlet:
#    context-path: /api
  port: 8091

spring:

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/flashsaleorders
    username: root
    password: nz321z1231997

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

springdoc:
  api-docs:
    path: /api-docs

