#server:
#  port: 8081
#spring:
#  application:
#    name: product-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/flashsaletemp
#    username: root
#    password: ucd21213011.
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
##        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
#  servlet:
#    context-path: /api
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/flashsaleproducts
    username: root
    password: nz321z1231997

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

springdoc:
  api-docs:
    path: /api-docs

