server:
  port: 8081
spring:
  application:
    name: userLogin-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///flashSale?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: nrah.520.
#jpa:
#  properties:
#    hibernate:
#      hbm2ddl:
#        auto: update
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect