#server:
#  port: 8091
#spring:
#  application:
#    name: order-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///shop-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: admin
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
#  servlet:
#    context-path: /api
  port: 8091

spring:

  cloud:
    nacos:
      discovery:
        server-addr: 52.215.184.45:8848

  application:
    name: order-service

  datasource:
    url: jdbc:mysql://flashsaledb.ccbk1nkjxq6v.eu-west-1.rds.amazonaws.com:3306/flashsaleorders
    username: admin
    password: PASSWORD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2000

springdoc:
  api-docs:
    path: /api-docs

