server:
  servlet:
    context-path: /api
  port: 8101

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/flashsalesellers
    username: root
    password: ucd21213011.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy

springdoc:
  api-docs:
    path: /api-docs

